###Hello world
GET http://localhost:3000/


### post report
POST http://localhost:3000/reports
content-type: application/json

{
  "make": "ford",
  "model": "mustag3",
  "year": 1982,
  "mileage": 15,
  "lng": 45,
  "lat": 45,
  "price": 20000
}

### approve report
PATCH http://localhost:3000/reports/12
content-type: application/json

{
  "approved":true
}

###
GET http://localhost:3000/reports?make=ford&model=mustag3&lng=45&lat=45&mileage=15&year=1981
