###Currently signedin user
GET http://localhost:3000/auth/whoami

### signin

POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email":"user1@abc.com",
    "password":"abc123"
}
###

GET http://localhost:3000/auth/signout
